### ISSUE TITLE
Windows carriage returns causing failure at run

### ISSUE THREAD

**Issue by hmaki** [OSSIndex/auditjs#12] opened 2017-04-29 20:41 UTC
I've got a script in Jenkins that runs auditjs as the last build step. Recently it started failing saying

/usr/bin/env: node
: No such file or directory

Apparently this is the first line of the audit.js file. The support engineer hosting the devops services said this is because there is Windows carriage return after node (notice the split lines in the error output), and the system can't find program named node\r.

I haven't heard of such issue before. In our support engineer right or could there be some other problem.

**Comment by OSSIndex-Admin** [comment] 2017-04-29 22:43
Heavy. It is possible, as I occasionally do work on my windows machine. I will dos2unix the whole thing and push a clean version (also do some testing to see if I can duplicate the issue).

**Comment by OSSIndex-Admin** [comment] 2017-04-30 01:54
It seems that the issue is that some Linux systems use `node` as the executable names, while some use `nodejs`, and we need to prepare for both. On your system the script was not finding `node`, hence the error message -- the \r only served to corrupt the error message.

I happen to have testing systems which represent both. I pushed a new version to npm and it seems to work on both my systems now. I am closing the issue, but definitely reopen if you still have issues on your side.

Thanks for the report!

**Comment by hmaki** [comment] 2017-05-09 17:09
Hi

We upgraded to auditjs v2.1.4 and now suddenly I'm seeing an odd error.

/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node.js_7.7.1/lib/node_modules/auditjs/audit.js:120
var output = `${programPackage.toString().split('.json').slice(0, -1)}.xml`;
             ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

Totally clueless why this happens. Any ideas?

**Comment by OSSIndex-Admin** [comment] 2017-05-09 18:04
Whoa. That's odd. I'm checking into it now...

**Comment by OSSIndex-Admin** [comment] 2017-05-09 18:15
My best guess at this moment is your installed version of node is quite old. The new code that was added tried to detect the appropriate nodejs command, first checking `nodejs`, then checking `node`. It is done through this command (line 2 of the main script)

```
$(command -v nodejs || command -v node)
```

Try running the following commands and send the results:
```
nodejs --version
node --version
```

I expect *one* of the commands likely fail in your case (hence the original issue), but we should get a version number from the other.

**Comment by hmaki** [comment] 2017-05-09 20:29
nodejs --version
v0.10.25
node --version
v7.7.1

**Comment by OSSIndex-Admin** [comment] 2017-05-10 02:08
Alright. Out of curiosity, is this the same machine as the original problem, or a different one? On the machine I was able to reproduce the original problem the issue was that node was installed under the name "nodejs" instead of "node". My other machines have node installed under the name "node" instead of "nodejs".

It appears on your current machine node is installed under both names, but the `nodejs` version is quite out of date.

As the "official" node.js binary name is `node` I can check there first. This has two possible issues:

1. Someone else might have a version problem in the other order as you
2. In theory a conflicting package on debian might have taken the "node" name and this will break the script if I check that one first.

The second issue should be rather rare, since I believe that the conflicting package is a hamradio package -- its likely fairly rare that it should crop up.

As I do not know which situation is more likely with regards to `node` or `nodejs` being out of date, perhaps I will just swap them around and see if there are complaints.

A *proper* fix would be to run both executables and do a version check (and ensure they are node) and choose the best one. This will be much more time consuming.

I think as a quick fix I will swap the order of the check and hope for the best, but leave this issue open pending a more complete fix. I will let you know when a new version is available with the hack/fix.

**Comment by OSSIndex-Admin** [comment] 2017-05-10 03:11
Ha. Alright, turns out the original problem for you really was likely the ^M character alone, since my yet a *different* test machine was able to reproduce your issue. Very curious that some machines seems to care about ^M and some don't. I was not solely an issue of a missing node command (as one of my other machines was inferring).

So now I look for `node` first and use that if possible, then fall back to `nodejs` if required (as is needed on some Debian/Ubuntu machines). This will still fail if someone has installed the `node` package on some old Debian/Ubuntu installations (which is not the same as nodejs) since the executable is something else entirely. This will hopefully be a rather rare situation.

*sigh*

Version 2.1.6 has been pushed to npm. It appears to be working on several of my test machines which have different situations set up. It *will* fail if the non-nodejs `node` is installed or if the nodejs `node` executable is an old version, but there is not a heck of a lot I can do quickly about that. I will need to write a preamble to the script which can identify the installed node version(s) and choose the best one, and I am disinclined to do that unless someone runs into a problem, and even then I will be somewhat angsty ;)

**Comment by hmaki** [comment] 2017-05-10 06:07
To your earlier question: yes, I ran it on the same machine. It appears to have both node and nodejs installed, with very different versions (nodejs being very old, as you said). Node version can be changed from the jenkins configuration GUI, but nodejs can't. The admins could if they bothered.

Just re-ran the builds having auditjs on, and it works now! I hope it doesn't break in other people's environments.

SO, BIG THANKS TO YOU!

**Comment by OSSIndex-Admin** [comment] 2017-05-23 04:02
No one has complained. It looks like we have a reasonably acceptable fix, so I will close the issue.

Thanks for the help.

**Closed by OSSIndex-Admin** 2017-05-23 04:02 UTC
